# Generated by Django 3.2.4 on 2021-07-13 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_level', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Senior Lecturer', 'Senior Lecturer'), ('Lecturer 1', 'Lecturer 1'), ('Lecturer 2', 'Lecturer 2'), ('Assistant Lecturer', 'Assistant Lecturer')], max_length=200)),
                ('department', models.CharField(choices=[('CIS', 'Computer and Information Science')], max_length=200)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supervisors',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('400 Level', '400 Level'), ('500 Level', '500 Level')], max_length=200)),
                ('department', models.CharField(choices=[('CIS', 'Computer and Information Science')], max_length=200)),
                ('course', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Management and Information Science', 'Management and Information Science')], max_length=200)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin')], max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='AreaOfInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Research', 'Research'), ('Implementation', 'Implementation'), ('Research + Implementation', 'Research + Implementation')], max_length=200, verbose_name='Category of Project')),
                ('first_choice', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Software Engineering', 'Software Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Algorithms', 'Algorithms'), ('Cloud Computing', 'Cloud Computing'), ('Networking and Communication', 'Networking and Communication'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Human Computer Interaction (HCI)', 'Human Computer Interaction (HCI)'), ('Machine Learning', 'Machine Learning'), ('Cyber Security', 'Cyber Security'), ('Information Systems', 'Information Systems'), ('Digital / Interactive Media', 'Digital / Interactive Media'), ('Game Design', 'Game Design'), ('Computer Graphics', 'Computer Graphics'), ('Web Development', 'Web Development'), ('Bioinformatics', 'Bioinformatics'), ('Database Management', 'Database Management'), ('Mobile Development', 'Mobile Development')], max_length=200, verbose_name='First Choice')),
                ('second_choice', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Software Engineering', 'Software Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Algorithms', 'Algorithms'), ('Cloud Computing', 'Cloud Computing'), ('Networking and Communication', 'Networking and Communication'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Human Computer Interaction (HCI)', 'Human Computer Interaction (HCI)'), ('Machine Learning', 'Machine Learning'), ('Cyber Security', 'Cyber Security'), ('Information Systems', 'Information Systems'), ('Digital / Interactive Media', 'Digital / Interactive Media'), ('Game Design', 'Game Design'), ('Computer Graphics', 'Computer Graphics'), ('Web Development', 'Web Development'), ('Bioinformatics', 'Bioinformatics'), ('Database Management', 'Database Management'), ('Mobile Development', 'Mobile Development')], max_length=200, verbose_name='Second Choice')),
                ('third_choice', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Software Engineering', 'Software Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Algorithms', 'Algorithms'), ('Cloud Computing', 'Cloud Computing'), ('Networking and Communication', 'Networking and Communication'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Human Computer Interaction (HCI)', 'Human Computer Interaction (HCI)'), ('Machine Learning', 'Machine Learning'), ('Cyber Security', 'Cyber Security'), ('Information Systems', 'Information Systems'), ('Digital / Interactive Media', 'Digital / Interactive Media'), ('Game Design', 'Game Design'), ('Computer Graphics', 'Computer Graphics'), ('Web Development', 'Web Development'), ('Bioinformatics', 'Bioinformatics'), ('Database Management', 'Database Management'), ('Mobile Development', 'Mobile Development')], max_length=200, verbose_name='Third Choice')),
                ('fourth_choice', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Software Engineering', 'Software Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Algorithms', 'Algorithms'), ('Cloud Computing', 'Cloud Computing'), ('Networking and Communication', 'Networking and Communication'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Human Computer Interaction (HCI)', 'Human Computer Interaction (HCI)'), ('Machine Learning', 'Machine Learning'), ('Cyber Security', 'Cyber Security'), ('Information Systems', 'Information Systems'), ('Digital / Interactive Media', 'Digital / Interactive Media'), ('Game Design', 'Game Design'), ('Computer Graphics', 'Computer Graphics'), ('Web Development', 'Web Development'), ('Bioinformatics', 'Bioinformatics'), ('Database Management', 'Database Management'), ('Mobile Development', 'Mobile Development')], max_length=200, verbose_name='Fourth Choice')),
                ('fifth_choice', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Software Engineering', 'Software Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Algorithms', 'Algorithms'), ('Cloud Computing', 'Cloud Computing'), ('Networking and Communication', 'Networking and Communication'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('Human Computer Interaction (HCI)', 'Human Computer Interaction (HCI)'), ('Machine Learning', 'Machine Learning'), ('Cyber Security', 'Cyber Security'), ('Information Systems', 'Information Systems'), ('Digital / Interactive Media', 'Digital / Interactive Media'), ('Game Design', 'Game Design'), ('Computer Graphics', 'Computer Graphics'), ('Web Development', 'Web Development'), ('Bioinformatics', 'Bioinformatics'), ('Database Management', 'Database Management'), ('Mobile Development', 'Mobile Development')], max_length=200, verbose_name='Fifth Choice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name_plural': 'Area of Interests',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Unallocated', 'Unallocated'), ('Allocated', 'Allocated')], max_length=200)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisors')),
            ],
        ),
    ]
