# Generated by Django 3.2.4 on 2021-07-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin')], max_length=200, null=True),
        ),
    ]
