# Generated by Django 3.2.4 on 2021-07-09 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_allocation_areaofinterest_student_supervisor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameModel(
            old_name='Supervisor',
            new_name='Supervisors',
        ),
    ]
