# Generated by Django 3.2.4 on 2021-07-17 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_adminstrators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminstrators',
            new_name='Administrators',
        ),
        migrations.AlterModelOptions(
            name='administrators',
            options={'verbose_name_plural': 'Administrators'},
        ),
    ]
