# Generated by Django 3.2.4 on 2021-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210717_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorContraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.IntegerField(verbose_name='Professor')),
                ('assoc_professor', models.IntegerField(verbose_name='Associate Professor')),
                ('senior_lect', models.IntegerField(verbose_name='Senior Lecturer')),
                ('lect_one', models.IntegerField(verbose_name='Lecturer 1')),
                ('lect_two', models.IntegerField(verbose_name='Lecturer 2')),
                ('assist', models.IntegerField(verbose_name='Assistant Lecturer')),
            ],
            options={
                'verbose_name_plural': 'Supervisor Constraints',
            },
        ),
    ]
