# Generated by Django 3.2.4 on 2021-07-10 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20210709_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaOfInterest',
            new_name='AreaOfInterests',
        ),
    ]
