# Generated by Django 3.2.4 on 2021-07-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_rename_areaofinterest_areaofinterests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterests',
            options={'verbose_name_plural': 'AreaOfInterests'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='supervisors',
            options={'verbose_name_plural': 'Supervisors'},
        ),
        migrations.AlterField(
            model_name='areaofinterests',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
