# Generated by Django 3.2.4 on 2021-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210717_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_interest', models.DateField(verbose_name='Area of Interest')),
                ('ranking', models.DateField(verbose_name='Ranking')),
                ('submit_profile', models.DateField(verbose_name='Submit Profile')),
                ('allocation_result', models.DateField(verbose_name='Allocation Result')),
            ],
            options={
                'verbose_name_plural': 'Registration Deadlines',
            },
        ),
        migrations.AlterModelOptions(
            name='supervisorranking',
            options={'verbose_name_plural': 'Supervisor Ranking'},
        ),
    ]
