# Generated by Django 3.2.4 on 2021-07-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210717_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentranking',
            name='fifth_choice',
        ),
        migrations.RemoveField(
            model_name='studentranking',
            name='first_choice',
        ),
        migrations.RemoveField(
            model_name='studentranking',
            name='fourth_choice',
        ),
        migrations.RemoveField(
            model_name='studentranking',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='studentranking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentranking',
            name='third_choice',
        ),
        migrations.RemoveField(
            model_name='supervisorranking',
            name='fifth_choice',
        ),
        migrations.RemoveField(
            model_name='supervisorranking',
            name='first_choice',
        ),
        migrations.RemoveField(
            model_name='supervisorranking',
            name='fourth_choice',
        ),
        migrations.RemoveField(
            model_name='supervisorranking',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='supervisorranking',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supervisorranking',
            name='third_choice',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='StudentRanking',
        ),
        migrations.DeleteModel(
            name='SupervisorRanking',
        ),
    ]
