# Generated by Django 3.2.4 on 2021-07-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20210710_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterests',
            options={'verbose_name_plural': 'Area of Interests'},
        ),
        migrations.RemoveField(
            model_name='areaofinterests',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='id',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.students'),
        ),
        migrations.AlterField(
            model_name='areaofinterests',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
