# Generated by Django 3.2.4 on 2021-07-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210718_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='unallocatedstudents',
            name='course',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='unallocatedstudents',
            name='department',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='unallocatedstudents',
            name='level',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='unallocatedsupervisors',
            name='department',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='unallocatedsupervisors',
            name='staff_level',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
