# Generated by Django 3.2.4 on 2021-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210719_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unallocatedstudents',
            name='fifth_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Fifth Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedstudents',
            name='first_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='First Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedstudents',
            name='fourth_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Fourth Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedstudents',
            name='second_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Second Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedstudents',
            name='third_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Third Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedsupervisors',
            name='fifth_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Fifth Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedsupervisors',
            name='first_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='First Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedsupervisors',
            name='fourth_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Fourth Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedsupervisors',
            name='second_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Second Choice'),
        ),
        migrations.AlterField(
            model_name='unallocatedsupervisors',
            name='third_choice',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence - Robotics, Data Science, Algorithm Design, Machine Learning'), ('Systems Engineering', 'Systems Engineering - Information Systems, Web Development, Mobile Development, Game Development, Software Development, Database Management'), ('Networking and Communication', 'Networking and Communication - Network Administration, Telecommunication, Cloud Computing'), ('Design and Animation', 'Design and Animation'), ('Cyber Security', 'Cyber Security')], default=None, max_length=200, verbose_name='Third Choice'),
        ),
    ]
