# Generated by Django 3.2.4 on 2021-07-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210719_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocated',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.unallocatedstudents'),
        ),
        migrations.AlterField(
            model_name='allocated',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unallocatedsupervisors'),
        ),
    ]
