# Generated by Django 3.2.4 on 2021-07-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210720_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdeadline',
            name='ranking',
        ),
    ]
